repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-executables-have-shebangs
        files: \.sh
      - id: check-json
      - id: check-vcs-permalinks
      - id: check-yaml
        exclude: ^helm/
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: local
    hooks:
      - id: eslint-prettier
        name: Lint and Style
        language: system
        files: \.(j|t)s$
        entry: ./.bin/eslint-prettier.sh
        pass_filenames: false
