replicaCount: 2

image:
  repository: launchonlineacr.azurecr.io/osf/webapp
  tag: blast
  pullPolicy: Always
  # pullPolicy: IfNotPresent

dbImage:
  repository: launchonlineacr.azurecr.io/osf/db

nameOverride: webapp
fullnameOverride: webapp

service:
  type: ClusterIP
  port: 3030
  sessionSecret: # this must be overridden and stored securely

ingress:
  enabled: true

  annotations:
    kubernetes.io/ingress.class: azure/application-gateway
    appgw.ingress.kubernetes.io/ssl-redirect: "true"
    cert-manager.io/cluster-issuer: letsencrypt-prod
    cert-manager.io/acme-challenge-type: http01

postgresql:
  enabled: false
  host:
  port:
  username:
  password:
  database:

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 11
  targetCPUUtilizationPercentage: 50
  targetMemoryUtilizationPercentage: 50
  customMetrics: []

resources:
  limits:
    cpu: 0.5
    memory: 512M
  requests:
    cpu: 0.25
    memory: 256M

nodeSelector: {}

tolerations: []

affinity: {}
