replicaCount: 1

image:
  repository: onlineshopsgrant.azurecr.io/osf/app
  tag: v0.1.0
  pullPolicy: Always
  # pullPolicy: IfNotPresent

nameOverride: osf-app
fullnameOverride: osf-app

service:
  type: LoadBalancer
  port: 80

ingress:
  enabled: false

  host: onlineshopsgrant.com
  paths: ['/']

  # tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

postgresql:
  enabled: false
  host:
  port:
  username: testadmin@onlineshopsgrant
  password:
  database:

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 11
  targetCPUUtilizationPercentage: 50
  targetMemoryUtilizationPercentage: 50
  customMetrics: []

securityContext:
  runAsUser: 1001
  runAsGroup: 1001
  fsGroup: 1001

resources:
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  #
  # see https://youtrack-support.jetbrains.com/hc/en-us/articles/206546119-What-hardware-requirements-does-YouTrack-have-
  limits:
    cpu: 0.5
    memory: 500M
  requests:
    cpu: 0.5
    memory: 500M

nodeSelector: {}

tolerations: []

affinity: {}
