apiVersion: batch/v1
kind: Job
metadata:
  name: postgres-setup
  labels:
    app.kubernetes.io/name: {{ include "..name" . }}
    helm.sh/chart: {{ include "..chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  annotations:
    "helm.sh/hook": "pre-install,pre-upgrade,pre-rollback"
    "helm.sh/hook-delete-policy": "before-hook-creation"
    "helm.sh/hook-weight": "2"
spec:
  template:
    spec:
      containers:
        - name: postgres-setup
          image: "{{ .Values.dbImage.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: Always
          envFrom:
            - secretRef:
                name: postgresql
            - secretRef:
                name: smtp

      restartPolicy: Never
  backoffLimit: 1
