{{- if .Values.postgresql.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: postgresql
  labels:
    app.kubernetes.io/name: {{ include "..name" . }}
    helm.sh/chart: {{ include "..chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
data:
  PGUSER: {{ .Values.postgresql.username | b64enc }}
  PGPASSWORD: {{ .Values.postgresql.password | b64enc }}
  PGHOST: {{ .Values.postgresql.host | b64enc }}
  PGPORT: {{ .Values.postgresql.port | b64enc }}
  PGDATABASE: {{ .Values.postgresql.database | b64enc }}
{{- end }}
