
ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: azure/application-gateway
    cert-manager.io/cluster-issuer: letsencrypt-prod
    cert-manager.io/acme-challenge-type: http01
  hosts:
    - host: test-mailhog.launchonline.ca
      paths: ["/"]
  tls:
    - secretName: test-mailhog-launchonline-tls
      hosts:
        - test-mailhog.launchonline.ca

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi

auth:
  enabled: true
  existingSecret: ""
  fileContents: "launchonline:<`N?qEk~W"^P]u8^"
