cas-postgres:
  patroni:
    persistentVolume:
      storageClass: default
    env:
      USE_WALG_BACKUP: "false"
      USE_WALG_RESTORE: "false"
    walE:
      enable: false
  namespace: dev-metabase

route:
  enable: false

networkSecurityPolicies:
  enable: false

ingress:
  enabled: true
