# see https://github.com/bcgov/cas-metabase/blob/develop/helm/cas-metabase/values.yaml

cas-postgres:
  patroni:
    image:
      tag: fd49e26f35a1ada65ad64bedd383aa4096a4f96f
    persistentVolume:
      storageClass: default
    env:
      USE_WALG_BACKUP: "false"
      USE_WALG_RESTORE: "false"
    walE:
      enable: false
  namespace: prod-metabase

metabase:
  timeZone: US/Pacific
  ingress:
    enabled: false

route:
  enable: false

networkSecurityPolicies:
  enable: false
