# see https://github.com/bcgov/cas-metabase/blob/develop/helm/cas-metabase/values.yaml

cas-postgres:
  patroni:
    image:
      tag: fd49e26f35a1ada65ad64bedd383aa4096a4f96f
    persistentVolume:
      storageClass: default
    env:
      USE_WALG_BACKUP: "false"
      USE_WALG_RESTORE: "false"
    walE:
      enable: false
  namespace: test-metabase

metabase:
  timeZone: US/Pacific
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: azure/application-gateway
      cert-manager.io/cluster-issuer: letsencrypt-prod
      cert-manager.io/acme-challenge-type: http01
    hosts:
      - test-metabase.launchonline.ca
    path: /
    tls:
      - secretName: test-metabase-launchonline-tls
        hosts:
          - test-metabase.launchonline.ca
  resources:
    limits:
      cpu: 1
      memory: 2Gi
    requests:
      cpu: 500m
      memory: 1Gi

route:
  enable: false

networkSecurityPolicies:
  enable: false
