name: Production Release

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag Version'
        required: true

env:
  env: prod
  tag: ${{ github.event.inputs.tag }}

jobs:
  build-deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Unlock secrets
        uses: sliteteam/github-action-git-crypt-unlock@1.0.2
        env:
          GIT_CRYPT_KEY: ${{ secrets.GIT_CRYPT_KEY }}

      - name: "Login via Azure CLI"
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: "Login to Docker Registry"
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: asdf_install
        uses: asdf-vm/actions/setup@v1

      - name: Deploy Helm Charts
        run: |
          cat .tool-versions | cut -f 1 -d ' ' | xargs -n 1 asdf plugin-add || true
          asdf plugin-update --all
          asdf install
          asdf reshim
          az aks get-credentials --resource-group launchonline-resource-group --name launchonline-aks
          make upgrade-app ENV=${{ env.env }} TAG=${{ env.tag }}
        working-directory: ./helm
